- hello4.txt
> sid-pull-request

- business_model_canvases.txt
This is my draft for the content on HW2 business model canvases. Thank you.
> business_model_canvases draft

- javilin_board.txt
Please review my Hypothesis Testing
> Kaihangchen hw4 p3

- javilin_board.txt
> Siddharth's HW4 P3

- business_model_canvases.txt
> modified business model canvas

- business_model_canvases.txt
> Sid - Add to business canvas

- business_model_canvases.txt
> added customer segment

- document/user_stories.md
> Sid User Stories

- document/persona.md
> Sid persona essay

- src/components/jobList.js
- src/pages/app.js
fix import statement causing compile error
> fix jobDescription compile issue

- query.js
- src/pages/businessProfile.js
1.add business_profile api
2.try to write a query to get data
> try to use query to get data

- amplify/backend/auth/cognitoed11de21/cognitoed11de21-cloudformation-template.yml
- amplify/backend/auth/cognitoed11de21/parameters.json
- amplify/team-provider-info.json
- src/components/form/postJob.js
- src/components/jobList/jobItem.js
- src/graphql/mutations.js
- src/graphql/queries.js
- src/graphql/schema.json
- src/graphql/subscriptions.js
- src/pages/jobList.js
Reverts Kaihchen1230/csc47300Project#149
> Revert "update posting job input and displaying job"

- src/components/user_profile/content.js
- src/components/user_profile/education.js
- src/customGraphql/queries.js
- src/pages/userProfile.js
Right now the education is in a table. I will change this to show in something else, like cards.
> display employee's education on profile

- package-lock.json
- package.json
- src/components/authentication/signup.js
- src/components/business_profile/EditProfileForm.js
- src/components/business_profile/postJob.js
- src/components/business_profile/video.js
- src/components/navBar.js
- src/pages/app.js
- src/pages/businessProfile.js
- src/pages/contact.js
1.change the contact page color
2.allow edit video url
3.change the user icon
> continue to design different pages

- src/components/user_profile/education.js
- src/pages/jobList.js
- src/pages/userProfile.js
items are now deleted from api and disappear from the screen if user presses delete button
> api can delete items

- docs/businessProfile.mdx
- docs/index.mdx
- src/components/authentication/login.js
- src/components/authentication/new_login.js
- src/components/business_profile/EditProfileForm.js
- src/components/business_profile/businessPicture.js
- src/components/business_profile/postJob.js
- src/components/business_profile/video.js
- src/components/user_profile/photo.css
- src/components/user_profile/photoUploader.js
- src/pages/businessProfile.js
- src/pages/userProfile.js
- src/style/businessProfile.css
Use allen's upload component to finish the upload company logo button
> add upload company logo button

- src/components/dictionary/dictionary.js
- src/components/form/addEducation.js
- src/components/form/addExperience.js
- src/components/user_profile/experiences.js
- src/pages/app.js
- src/pages/userProfile.js
> add experience form

- amplify/backend/api/csc47300project/build/cloudformation-template.json
- amplify/backend/api/csc47300project/build/parameters.json
- amplify/backend/awscloudformation/nested-cloudformation-stack.yml
- src/components/form/addEducation.js
- src/components/form/addExperience.js
- src/components/form/updateAddress.js
- src/graphql/schema.json
- src/pages/userProfile.js
the form needs to be tested but right now I am unable to because there is an error when clicking on the user profile page
> work on update address form

- src/components/authentication/login.js
- src/components/business_profile/video.css
- src/components/business_profile/video.js
- src/components/job_description/companyDetail.js
- src/components/job_description/jobDetails.js
- src/components/job_description/locationDetail.js
- src/components/navBar.js
- src/pages/businessProfile.js
- src/pages/jobDescription.js
- src/style/businessProfile.css
- src/style/jobDescription.css
- src/style/nav.css
1.change the job description design
2. make the video component on business profile page more responsive
> change design

- src/components/form/addEducation.js
- src/components/form/addExperience.js
- src/components/form/createAddress.js
- src/components/form/updateAddress.js
- src/components/user_profile/appliedJob.js
- src/components/user_profile/education.js
- src/components/user_profile/experiences.js
- src/components/user_profile/general.js
- src/pages/contact.js
the html doc pages for these comments need to be generated
> add documentation comments

- docs/UpdateAddressForm.html
Reverts Kaihchen1230/csc47300Project#339
> Revert "remove update form html"

- docs/index.html
Reverts Kaihchen1230/csc47300Project#337
> Revert "fix index.html"

- src/components/job_description/locationDetail.js
Reverts Kaihchen1230/csc47300Project#331
> Revert "key"

- package.json
Reverts Kaihchen1230/csc47300Project#329
> Revert "modify build command"
